/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FlowPayEscrow {
  export type EscrowStruct = {
    id: BigNumberish;
    client: AddressLike;
    freelancer: AddressLike;
    amount: BigNumberish;
    createdAt: BigNumberish;
    deadline: BigNumberish;
    submittedAt: BigNumberish;
    disputedAt: BigNumberish;
    status: BigNumberish;
    description: string;
  };

  export type EscrowStructOutput = [
    id: bigint,
    client: string,
    freelancer: string,
    amount: bigint,
    createdAt: bigint,
    deadline: bigint,
    submittedAt: bigint,
    disputedAt: bigint,
    status: bigint,
    description: string
  ] & {
    id: bigint;
    client: string;
    freelancer: string;
    amount: bigint;
    createdAt: bigint;
    deadline: bigint;
    submittedAt: bigint;
    disputedAt: bigint;
    status: bigint;
    description: string;
  };
}

export interface FlowPayEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_TIMEOUT"
      | "MAX_DESCRIPTION_LENGTH"
      | "MAX_DURATION"
      | "REVIEW_PERIOD"
      | "acceptOwnership"
      | "claimAfterReview"
      | "createEscrow"
      | "escrowIdCounter"
      | "getClientEscrowIds"
      | "getEscrow"
      | "getFreelancerEscrowIds"
      | "initiateDispute"
      | "owner"
      | "pendingOwner"
      | "refundAfterDeadline"
      | "refundByFreelancer"
      | "releaseFunds"
      | "resolveDispute"
      | "resolveDisputeByTimeout"
      | "submitWork"
      | "token"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeInitiated"
      | "DisputeResolved"
      | "EscrowCreated"
      | "FundsClaimedAfterReview"
      | "FundsReleased"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Refunded"
      | "WorkSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DESCRIPTION_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REVIEW_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimAfterReview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getClientEscrowIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFreelancerEscrowIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundAfterDeadline",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundByFreelancer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDisputeByTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DESCRIPTION_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REVIEW_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAfterReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClientEscrowIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFreelancerEscrowIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundAfterDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundByFreelancer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDisputeByTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitWork", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DisputeInitiatedEvent {
  export type InputTuple = [escrowId: BigNumberish, initiatedBy: AddressLike];
  export type OutputTuple = [escrowId: bigint, initiatedBy: string];
  export interface OutputObject {
    escrowId: bigint;
    initiatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    toClient: BigNumberish,
    toFreelancer: BigNumberish,
    byTimeout: boolean
  ];
  export type OutputTuple = [
    escrowId: bigint,
    toClient: bigint,
    toFreelancer: bigint,
    byTimeout: boolean
  ];
  export interface OutputObject {
    escrowId: bigint;
    toClient: bigint;
    toFreelancer: bigint;
    byTimeout: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    client: AddressLike,
    freelancer: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish,
    description: string
  ];
  export type OutputTuple = [
    escrowId: bigint,
    client: string,
    freelancer: string,
    amount: bigint,
    deadline: bigint,
    description: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    client: string;
    freelancer: string;
    amount: bigint;
    deadline: bigint;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsClaimedAfterReviewEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    freelancer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    freelancer: string,
    amount: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    freelancer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    freelancer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    freelancer: string,
    amount: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    freelancer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    client: AddressLike,
    amount: BigNumberish,
    initiatedBy: AddressLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    client: string,
    amount: bigint,
    initiatedBy: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    client: string;
    amount: bigint;
    initiatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkSubmittedEvent {
  export type InputTuple = [escrowId: BigNumberish, freelancer: AddressLike];
  export type OutputTuple = [escrowId: bigint, freelancer: string];
  export interface OutputObject {
    escrowId: bigint;
    freelancer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlowPayEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): FlowPayEscrow;
  waitForDeployment(): Promise<this>;

  interface: FlowPayEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  MAX_DESCRIPTION_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MAX_DURATION: TypedContractMethod<[], [bigint], "view">;

  REVIEW_PERIOD: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  claimAfterReview: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [
      _freelancer: AddressLike,
      _amount: BigNumberish,
      _deadline: BigNumberish,
      _description: string
    ],
    [bigint],
    "nonpayable"
  >;

  escrowIdCounter: TypedContractMethod<[], [bigint], "view">;

  getClientEscrowIds: TypedContractMethod<
    [client: AddressLike],
    [bigint[]],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [id: BigNumberish],
    [FlowPayEscrow.EscrowStructOutput],
    "view"
  >;

  getFreelancerEscrowIds: TypedContractMethod<
    [freelancer: AddressLike],
    [bigint[]],
    "view"
  >;

  initiateDispute: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  refundAfterDeadline: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  refundByFreelancer: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseFunds: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [id: BigNumberish, toFreelancer: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveDisputeByTimeout: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitWork: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DESCRIPTION_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REVIEW_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimAfterReview"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      _freelancer: AddressLike,
      _amount: BigNumberish,
      _deadline: BigNumberish,
      _description: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrowIdCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getClientEscrowIds"
  ): TypedContractMethod<[client: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [id: BigNumberish],
    [FlowPayEscrow.EscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFreelancerEscrowIds"
  ): TypedContractMethod<[freelancer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "initiateDispute"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundAfterDeadline"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refundByFreelancer"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [id: BigNumberish, toFreelancer: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDisputeByTimeout"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitWork"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DisputeInitiated"
  ): TypedContractEvent<
    DisputeInitiatedEvent.InputTuple,
    DisputeInitiatedEvent.OutputTuple,
    DisputeInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FundsClaimedAfterReview"
  ): TypedContractEvent<
    FundsClaimedAfterReviewEvent.InputTuple,
    FundsClaimedAfterReviewEvent.OutputTuple,
    FundsClaimedAfterReviewEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "WorkSubmitted"
  ): TypedContractEvent<
    WorkSubmittedEvent.InputTuple,
    WorkSubmittedEvent.OutputTuple,
    WorkSubmittedEvent.OutputObject
  >;

  filters: {
    "DisputeInitiated(uint256,address)": TypedContractEvent<
      DisputeInitiatedEvent.InputTuple,
      DisputeInitiatedEvent.OutputTuple,
      DisputeInitiatedEvent.OutputObject
    >;
    DisputeInitiated: TypedContractEvent<
      DisputeInitiatedEvent.InputTuple,
      DisputeInitiatedEvent.OutputTuple,
      DisputeInitiatedEvent.OutputObject
    >;

    "DisputeResolved(uint256,uint256,uint256,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EscrowCreated(uint256,address,address,uint256,uint256,string)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "FundsClaimedAfterReview(uint256,address,uint256)": TypedContractEvent<
      FundsClaimedAfterReviewEvent.InputTuple,
      FundsClaimedAfterReviewEvent.OutputTuple,
      FundsClaimedAfterReviewEvent.OutputObject
    >;
    FundsClaimedAfterReview: TypedContractEvent<
      FundsClaimedAfterReviewEvent.InputTuple,
      FundsClaimedAfterReviewEvent.OutputTuple,
      FundsClaimedAfterReviewEvent.OutputObject
    >;

    "FundsReleased(uint256,address,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Refunded(uint256,address,uint256,address)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "WorkSubmitted(uint256,address)": TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
    WorkSubmitted: TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
  };
}
